### ISSUE TITLE
Discover / Leviers

### ISSUE THREAD

**Issue by RemyChambardW** [edhelas/metawatt#1]
La phrase d’introduction annonce 3 grands leviers. Avec la présentation qui suit, on en voit facilement 2, mais le 3ème est bizarre puisqu’il fait beaucoup référence aux 2 premiers. 
Je propose donc de préfixer par un nombre 1 à 3 ou I à III, pour aider le lecteur à se repérer sur la page.

**Comment by edhelas** [comment]
Corrigé ;)
