### ISSUE TITLE
Scénario / Comparateur CO2

### ISSUE THREAD

**Issue by RemyChambardW** [edhelas/metawatt#13]
PArmis les sources d'énergie, dont les noms sont en anglais ou en abrégé d'anglais d'ailleurs, il y a un truc que je ne connais pas : Tidal !
Et personne ne semble en utiliser. 
Question : Ne serait-ce pas une donnée en trop dans les data ? Ou un truc secret pour TerraWater?

**Comment by edhelas** [comment]
Tidal :)

![image](https://user-images.githubusercontent.com/3726886/200116924-1250a2cc-3be0-4d3a-88e2-e38fad24c064.png)
