### ISSUE TITLE
Capacité installée nucléaire historique en 2050 pour RTE N1

### ISSUE THREAD

**Issue by buchanan-fh** [edhelas/metawatt#15]
Il semble y avoir un écart entre les données publiées par RTE et celle renseignées dans metawatt:

|N1 RTE|N1 RTE metawatt|
|---|---|
|63,1|63,1|
|59,4|59,4|
|43,1|43,1|
|***15,5***|***25,5***|
|1,6|1,6|

**Comment by edhelas** [comment]
Je regarde ça merci !
