### ISSUE TITLE
Impact / Couleur des graphiques 

### ISSUE THREAD

**Issue by RemyChambardW** [edhelas/metawatt#17]
Pour les comparateurs en graphique à barres, certaines couleurs semblent trop proches, surtout l'une à coté de l'autre.

C'est le cas pour Wind et HydroWind, sachant que Step n'est pas visible,
C'est le cas encore plus pour Nuc versus New nuc

On retrouve le problème sur le surprenant graphique "part de production" sous la production totale, avec des % pas toujours lisibles sur le jaune.

**Comment by edhelas** [comment]
Corrigé ;)
