### ISSUE TITLE
Energie / Nucléaire / Capacité déployée dans le temps

### ISSUE THREAD

**Issue by RemyChambardW** [edhelas/metawatt#19]
Je ne comprends pas pourquoi l'énergie nucléaire associée au projet TerraWater décroit en 205 0 et encore plus en 2060.
Il y a un illogisme pour moi. Mais c'est peut être la définition de la courbe que je n'ai pas comprise.

**Comment by edhelas** [comment]
Nucléaire existant/nouveau nucléaire
