### ISSUE TITLE
Discover / Chap Efficacité

### ISSUE THREAD

**Issue by RemyChambardW** [edhelas/metawatt#2]
4ème § « Les différents scénarios proposés sur Metawatt »
Pour moi, les scénarios comme indiqués plus haut sont « analysés ». C’est pas Metawatt qui les proposent. 

Proposition « Les différents scénarios analysés sur Metawatt proposent plusieurs … »

Pb dans le même §, je propose de faire 2 phrases, en finissant la première à «  sur notre territoire. » puis en commençant « Certains scénarios estiment ».

**Comment by edhelas** [comment]
Corrigé ;)
