### ISSUE TITLE
Unité émission de CO2

### ISSUE THREAD

**Issue by HugoAH** [edhelas/metawatt#27]
Faute de frappe dans l'unité en ordonnée du graph "Émission dans le temps".
Il est indiqué MT alors que les valeurs sont en kt (il faudrait préciser si ce sont du CO2 ou du CO2eq également).
Je suggère de remplacer "MT" par "kt CO2eq".

**Comment by edhelas** [comment]
Merci, je vais corriger ça rapidement ;)
