### ISSUE TITLE
Discover / Efficacité / 5ème §

### ISSUE THREAD

**Issue by RemyChambardW** [edhelas/metawatt#3]
Pb dans le chapitre « L’efficacité », 5ème §. Utilisation du mot outil qui ne répond pas au 1er § où l’on parle de objets et machine.

Proposition : « Nous avons néanmoins tendance à augmenter par la suite l'usage de cet outil annulant une partie ou la totalité du gain engendré par les améliorations d'efficacité apportées. » 
devient  
« Nous avons néanmoins tendance à augmenter par la suite l'usage de ces objets ou machines, annulant une partie ou la totalité du gain engendré par les améliorations d'efficacité apportées. »

**Comment by edhelas** [comment]
Corrigé :)
