### ISSUE TITLE
Discover / Sobriété / 1er §

### ISSUE THREAD

**Issue by RemyChambardW** [edhelas/metawatt#4]
Pb dans le chapitre « La sobriété », 1er §. « produits et consommés » à la fin, qui sont utilisés comme des verbes, peuvent être confondus avec des mots. Cela provoque une difficulté de lecture. 

Proposition : « Ce concept politique se traduit notamment par la limitation, à un niveau suffisant, des biens et services, produits et consommés. »
devient
 « Ce concept politique se traduit notamment par la limitation de la production et de la consommation des biens et services à un niveau bas mais suffisant. »
Remarque : J’ai ajouté « bas mais » dans la proposition.

**Comment by edhelas** [comment]
Corrigé :)
