### ISSUE TITLE
Discover / Sobriété / 2ème §

### ISSUE THREAD

**Issue by RemyChambardW** [edhelas/metawatt#5]
Pb dans le chapitre « La sobriété », 2ème §.Il manque 1 mot dans la 2ème phrase, sans doute « consommation »

« De nombreux comportements et modes de devront changer afin de s'assurer que nous restons dans les trajectoires. » 
devient
« De nombreux comportements et modes de consommation devront changer afin de s'assurer que nous restons dans les trajectoires. »

**Comment by edhelas** [comment]
Corrigé :)
