### ISSUE TITLE
Discover / Réduction des émissions / 1er §

### ISSUE THREAD

**Issue by RemyChambardW** [edhelas/metawatt#6]
Pb dans le chapitre « La réduction des émission », 1ère phrase, pb de grammaire (suffira) et d’orthographe (obectif)

Proposition : « Pour finalement s'assurer d'atteindre l'obectif de l'Accord de Paris l'efficacité et la sobriété ne suffira pas. » 
devient
« Pour finalement s'assurer d'atteindre l'objectif de l'Accord de Paris l'efficacité et la sobriété ne suffiront pas. »

Pb dans le chapitre « La réduction des émission », 1èr § après sobre, une virgule manque.

**Comment by edhelas** [comment]
Corrigé ! Merci :)
