### ISSUE TITLE
Scenarios / Ademe / 1er §

### ISSUE THREAD

**Issue by RemyChambardW** [edhelas/metawatt#7]
Le nombre de scénarios indiqué dans le 1er § , quatre, ne correspond pas au nombre de scénarios présenté puisque il y a les versions S3 Nuc et S3 Offshore

Proposition : passage de "quatre" à "cinq"
L’ADEME a souhaité soumettre au débat cinq chemins “types” cohérents qui présentent de manière volontairement contrastée des options économiques, techniques et de société pour atteindre la neutralité carbone en 2050.

**Comment by edhelas** [comment]
L'ADEME présente réellement 4 scénario dont un avec 2 variantes, j'ai corrigé en ce sens
