### ISSUE TITLE
Scénarios / ha artificialisés

### ISSUE THREAD

**Issue by RemyChambardW** [edhelas/metawatt#8]
Sur tous les scénarios, il y a une comparaison avec les surfaces artificialisées.

Faudrait-il mettre les hypothèses de bases à ce chiffre ? Par exemple la surface comptabilisée par type d'équipement.
Cet après-midi, j'ai fait l'hypothèse d'une surface de 500m / 500 m pour une éolienne en surface occupée, mais ce n'est pas de l'artificialisation. 
Peut être faut il parler d'occupation d'espace aussi ?

**Comment by edhelas** [comment]
Comme précisé j'ai pris la valeur du tableau RTE pour mon ratio, cité en bas de la page ici https://metawatt.fr/impact/resources/space/final

![image](https://user-images.githubusercontent.com/3726886/200087796-2aa69bcb-1506-43e5-9c8d-efc72b7d4716.png)
