### ISSUE TITLE
Scénarios / Ha artificialisés

### ISSUE THREAD

**Issue by RemyChambardW** [edhelas/metawatt#9]
L'hectare est une unité de mesure utilisée dans l'agriculture, mais il me semble que les habitants des villes réfléchissent  plus en kilomètres carrés. 
On trouve facilement Paris à 105 km2, pas à 10 500 ha sur le net.
Mais je comprends que cela divise tout par 100
D'un autre côté, sur le graphique du comparateur, les ordonnées sont en milliers d'ha, avec une unité en k ha qui est très bizare pour ne pas dire wtf ;=)

Proposition mais pas demande impérative : Passer en km2

**Comment by edhelas** [comment]
Pour le moment je reste sur de l'ha ;) Je verrais plus tard
